site_name: Pixkit Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
  favicon: assets/images/pixmoving.png
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - awesome-pages
  - macros
  - mkdocs-video
  - search
repo_url: https://github.com/pixmoving-moveit/pixkit-documentation